//
// BatchesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class BatchesAPI {
    /**
     Delete Multiple Invites
     
     - parameter identifierList: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the result
     */
    open class func batchDeleteInvites(identifierList: IdentifierList? = nil, apiResponseQueue: DispatchQueue = GuestSDKAPI.apiResponseQueue, completion: @escaping ((_ result: Swift.Result<BatchJob, Error>) -> Void)) {
        batchDeleteInvitesWithRequestBuilder(identifierList: identifierList).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(.success(response.body!))
            case let .failure(error):
                completion(.failure(error))
            }
        }
    }

    /**
     Delete Multiple Invites
     - POST /invites/batch_delete
     - Queues up a \"delete\" background task for one or more `Invite` entities.
     - parameter identifierList: (body)  (optional)
     - returns: RequestBuilder<BatchJob> 
     */
    open class func batchDeleteInvitesWithRequestBuilder(identifierList: IdentifierList? = nil) -> RequestBuilder<BatchJob> {
        let path = "/invites/batch_delete"
        let URLString = GuestSDKAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: identifierList)

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<BatchJob>.Type = GuestSDKAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Get a BatchJob
     
     - parameter batchId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the result
     */
    open class func getBatch(batchId: String, apiResponseQueue: DispatchQueue = GuestSDKAPI.apiResponseQueue, completion: @escaping ((_ result: Swift.Result<BatchJob, Error>) -> Void)) {
        getBatchWithRequestBuilder(batchId: batchId).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(.success(response.body!))
            case let .failure(error):
                completion(.failure(error))
            }
        }
    }

    /**
     Get a BatchJob
     - GET /batches/{batch_id}
     - Retrieve a given `BatchJob` entity.
     - parameter batchId: (path)  
     - returns: RequestBuilder<BatchJob> 
     */
    open class func getBatchWithRequestBuilder(batchId: String) -> RequestBuilder<BatchJob> {
        var path = "/batches/{batch_id}"
        let batchIdPreEscape = "\(APIHelper.mapValueToPathItem(batchId))"
        let batchIdPostEscape = batchIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{batch_id}", with: batchIdPostEscape, options: .literal, range: nil)
        let URLString = GuestSDKAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<BatchJob>.Type = GuestSDKAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

}
