//
// BatchJob.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The root of the BatchJob&#39;s schema. */
public struct BatchJob: Codable { 


    public var bid: String?
    public var createdAt: String?
    public var status: String?
    public var totalRecords: Int?
    public var workerName: String?
    public var user: User?
    public var pending: Int?
    public var completed: Int?
    public var failed: Int?

    public init(bid: String?, createdAt: String?, status: String?, totalRecords: Int?, workerName: String?, user: User?, pending: Int?, completed: Int?, failed: Int?) {
        self.bid = bid
        self.createdAt = createdAt
        self.status = status
        self.totalRecords = totalRecords
        self.workerName = workerName
        self.user = user
        self.pending = pending
        self.completed = completed
        self.failed = failed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case bid
        case createdAt = "created_at"
        case status
        case totalRecords = "total_records"
        case workerName = "worker_name"
        case user
        case pending
        case completed
        case failed
    }

}
