//
// GroupVisit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The data structure for a Group Visit object. Also called an Appointment. */
public struct GroupVisit: Codable { 


    public var id: Int?
    public var location: Location?
    public var hosts: [Host]?
    public var name: String?
    public var startTime: String?
    public var endTime: String?
    public var createdAt: String?
    public var updatedAt: String?
    public var registrationLimit: Int?
    public var registrationUrl: String?
    public var invitesCount: Int?
    public var unconfirmedRegistrationsCount: Int?
    public var manualRegistrationApproval: Bool?
    public var publicRegistrationEnabled: Bool?

    public init(id: Int?, location: Location?, hosts: [Host]?, name: String?, startTime: String?, endTime: String?, createdAt: String?, updatedAt: String?, registrationLimit: Int?, registrationUrl: String?, invitesCount: Int?, unconfirmedRegistrationsCount: Int?, manualRegistrationApproval: Bool?, publicRegistrationEnabled: Bool?) {
        self.id = id
        self.location = location
        self.hosts = hosts
        self.name = name
        self.startTime = startTime
        self.endTime = endTime
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.registrationLimit = registrationLimit
        self.registrationUrl = registrationUrl
        self.invitesCount = invitesCount
        self.unconfirmedRegistrationsCount = unconfirmedRegistrationsCount
        self.manualRegistrationApproval = manualRegistrationApproval
        self.publicRegistrationEnabled = publicRegistrationEnabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case location
        case hosts
        case name
        case startTime = "start_time"
        case endTime = "end_time"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case registrationLimit = "registration_limit"
        case registrationUrl = "registration_url"
        case invitesCount = "invites_count"
        case unconfirmedRegistrationsCount = "unconfirmed_registrations_count"
        case manualRegistrationApproval = "manual_registration_approval"
        case publicRegistrationEnabled = "public_registration_enabled"
    }

}
