//
// GroupVisitCreateParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct GroupVisitCreateParams: Codable, Hashable {

    public var name: String
    public var startTime: String
    public var endTime: String
    public var locationId: Int
    public var registrationLimit: Int?
    public var manualRegistrationApproval: Bool?
    public var publicRegistrationEnabled: Bool?
    public var hostIds: [Int]?

    public init(name: String, startTime: String, endTime: String, locationId: Int, registrationLimit: Int? = nil, manualRegistrationApproval: Bool? = nil, publicRegistrationEnabled: Bool? = nil, hostIds: [Int]? = nil) {
        self.name = name
        self.startTime = startTime
        self.endTime = endTime
        self.locationId = locationId
        self.registrationLimit = registrationLimit
        self.manualRegistrationApproval = manualRegistrationApproval
        self.publicRegistrationEnabled = publicRegistrationEnabled
        self.hostIds = hostIds
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case startTime = "start_time"
        case endTime = "end_time"
        case locationId = "location_id"
        case registrationLimit = "registration_limit"
        case manualRegistrationApproval = "manual_registration_approval"
        case publicRegistrationEnabled = "public_registration_enabled"
        case hostIds = "host_ids"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(startTime, forKey: .startTime)
        try container.encode(endTime, forKey: .endTime)
        try container.encode(locationId, forKey: .locationId)
        try container.encodeIfPresent(registrationLimit, forKey: .registrationLimit)
        try container.encodeIfPresent(manualRegistrationApproval, forKey: .manualRegistrationApproval)
        try container.encodeIfPresent(publicRegistrationEnabled, forKey: .publicRegistrationEnabled)
        try container.encodeIfPresent(hostIds, forKey: .hostIds)
    }



}
