//
// GroupVisitUpdateParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The allowable changes when updating a Group Visit (Appointment). */
public struct GroupVisitUpdateParams: Codable { 


    public var name: String?
    public var startTime: String?
    public var endTime: String?
    public var locationId: Int?
    public var registrationLimit: Int?
    public var manualRegistrationApproval: Bool?
    public var publicRegistrationEnabled: Bool?
    public var hostIds: [Int]?
    public var inviteIds: [Int]?
    public var refreshRegistrationUrl: Bool?

    public init(name: String?, startTime: String?, endTime: String?, locationId: Int?, registrationLimit: Int?, manualRegistrationApproval: Bool?, publicRegistrationEnabled: Bool?, hostIds: [Int]?, inviteIds: [Int]?, refreshRegistrationUrl: Bool?) {
        self.name = name
        self.startTime = startTime
        self.endTime = endTime
        self.locationId = locationId
        self.registrationLimit = registrationLimit
        self.manualRegistrationApproval = manualRegistrationApproval
        self.publicRegistrationEnabled = publicRegistrationEnabled
        self.hostIds = hostIds
        self.inviteIds = inviteIds
        self.refreshRegistrationUrl = refreshRegistrationUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case name
        case startTime = "start_time"
        case endTime = "end_time"
        case locationId = "location_id"
        case registrationLimit = "registration_limit"
        case manualRegistrationApproval = "manual_registration_approval"
        case publicRegistrationEnabled = "public_registration_enabled"
        case hostIds = "host_ids"
        case inviteIds = "invite_ids"
        case refreshRegistrationUrl = "refresh_registration_url"
    }

}
