//
// HostBatchCreateParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct HostBatchCreateParams: Codable { 


    public var hosts: [Any]?

    public init(hosts: [Any]?) {
        self.hosts = hosts
    }

}
