//
// IdentifierList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct IdentifierList: Codable { 


    public var ids: [String]?

    public init(ids: [String]?) {
        self.ids = ids
    }

}
