//
// InviteWatchlist.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** The root of the InviteWatchlist type&#39;s schema. */
public struct InviteWatchlist: Codable, Hashable {

    public var id: Int
    public var _internal: [InternalWatchlistResult]?
    public var external: [ExternalWatchlistResult]?
    /** Deprecated */
    public var internalColours: [String]?
    /** Deprecated */
    public var externalColours: [String]?

    public init(id: Int, _internal: [InternalWatchlistResult]? = nil, external: [ExternalWatchlistResult]? = nil, internalColours: [String]? = nil, externalColours: [String]? = nil) {
        self.id = id
        self._internal = _internal
        self.external = external
        self.internalColours = internalColours
        self.externalColours = externalColours
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case _internal = "internal"
        case external
        case internalColours = "internal_colours"
        case externalColours = "external_colours"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(_internal, forKey: ._internal)
        try container.encodeIfPresent(external, forKey: .external)
        try container.encodeIfPresent(internalColours, forKey: .internalColours)
        try container.encodeIfPresent(externalColours, forKey: .externalColours)
    }



}
