//
// InviteDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** The root of the InviteDetail type&#39;s schema. */
public struct InviteDetail: Codable, Hashable {

    public enum WatchlistColour: String, Codable, CaseIterable {
        case red = "RED"
        case green = "GREEN"
        case yellow = "YELLOW"
        case orange = "ORANGE"
    }
    public var id: Int
    public var registration: Registration?
    /** Phone number */
    public var mobileNumber: String?
    public var emailTemplate: EmailTemplate?
    public var inviteWatchlist: InviteWatchlist?
    /** List of scheduled notifications for an invite */
    public var notificationTriggers: [NotificationTrigger]?
    public var customFields: [CustomField]?
    public var watchlistColour: WatchlistColour?
    public var location: Location?
    public var hosts: [Host]?
    public var startDate: Date?
    public var lastName: String
    public var firstName: String
    public var endDate: Date?
    public var email: String
    public var createdAt: Date?
    public var company: String?
    public var checkedIn: Bool?
    public var groupVisit: GroupVisit?

    public init(id: Int, registration: Registration? = nil, mobileNumber: String? = nil, emailTemplate: EmailTemplate? = nil, inviteWatchlist: InviteWatchlist? = nil, notificationTriggers: [NotificationTrigger]? = nil, customFields: [CustomField]? = nil, watchlistColour: WatchlistColour? = nil, location: Location? = nil, hosts: [Host]? = nil, startDate: Date? = nil, lastName: String, firstName: String, endDate: Date? = nil, email: String, createdAt: Date? = nil, company: String? = nil, checkedIn: Bool? = nil, groupVisit: GroupVisit? = nil) {
        self.id = id
        self.registration = registration
        self.mobileNumber = mobileNumber
        self.emailTemplate = emailTemplate
        self.inviteWatchlist = inviteWatchlist
        self.notificationTriggers = notificationTriggers
        self.customFields = customFields
        self.watchlistColour = watchlistColour
        self.location = location
        self.hosts = hosts
        self.startDate = startDate
        self.lastName = lastName
        self.firstName = firstName
        self.endDate = endDate
        self.email = email
        self.createdAt = createdAt
        self.company = company
        self.checkedIn = checkedIn
        self.groupVisit = groupVisit
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case registration
        case mobileNumber = "mobile_number"
        case emailTemplate = "email_template"
        case inviteWatchlist = "invite_watchlist"
        case notificationTriggers = "notification_triggers"
        case customFields = "custom_fields"
        case watchlistColour = "watchlist_colour"
        case location
        case hosts
        case startDate = "start_date"
        case lastName = "last_name"
        case firstName = "first_name"
        case endDate = "end_date"
        case email
        case createdAt = "created_at"
        case company
        case checkedIn = "checked_in"
        case groupVisit = "group_visit"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(registration, forKey: .registration)
        try container.encodeIfPresent(mobileNumber, forKey: .mobileNumber)
        try container.encodeIfPresent(emailTemplate, forKey: .emailTemplate)
        try container.encodeIfPresent(inviteWatchlist, forKey: .inviteWatchlist)
        try container.encodeIfPresent(notificationTriggers, forKey: .notificationTriggers)
        try container.encodeIfPresent(customFields, forKey: .customFields)
        try container.encodeIfPresent(watchlistColour, forKey: .watchlistColour)
        try container.encodeIfPresent(location, forKey: .location)
        try container.encodeIfPresent(hosts, forKey: .hosts)
        try container.encodeIfPresent(startDate, forKey: .startDate)
        try container.encode(lastName, forKey: .lastName)
        try container.encode(firstName, forKey: .firstName)
        try container.encodeIfPresent(endDate, forKey: .endDate)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(company, forKey: .company)
        try container.encodeIfPresent(checkedIn, forKey: .checkedIn)
        try container.encodeIfPresent(groupVisit, forKey: .groupVisit)
    }



}
