//
// InviteCreateParamsParkingStall.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InviteCreateParamsParkingStall: Codable { 


    public var stallNumber: Int?
    public var parkingLotId: Int?
    public var parkingStallId: Int?

    public init(stallNumber: Int?, parkingLotId: Int?, parkingStallId: Int?) {
        self.stallNumber = stallNumber
        self.parkingLotId = parkingLotId
        self.parkingStallId = parkingStallId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case stallNumber = "stall_number"
        case parkingLotId = "parking_lot_id"
        case parkingStallId = "parking_stall_id"
    }

}
