//
// InviteCreateParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** The root of the InviteCreateParams type&#39;s schema. */
public struct InviteCreateParams: Codable, Hashable {

    public enum WatchlistColour: String, Codable, CaseIterable {
        case red = "RED"
        case green = "GREEN"
        case yellow = "YELLOW"
        case orange = "ORANGE"
    }
    public var mobileNumber: String?
    public var notificationTriggers: [NotificationTriggerCreateParams]?
    public var firstName: String
    public var emailTemplateId: Int?
    public var customFields: [CustomField]?
    public var hostIds: [Int]?
    public var watchlistColour: WatchlistColour?
    public var title: String?
    /** The &#x60;start_date&#x60; is required for invitations to lobbies */
    public var startDate: Date?
    public var lastName: String
    public var endDate: Date?
    public var email: String
    public var company: String?
    public var groupVisitId: Int?

    public init(mobileNumber: String? = nil, notificationTriggers: [NotificationTriggerCreateParams]? = nil, firstName: String, emailTemplateId: Int? = nil, customFields: [CustomField]? = nil, hostIds: [Int]? = nil, watchlistColour: WatchlistColour? = nil, title: String? = nil, startDate: Date? = nil, lastName: String, endDate: Date? = nil, email: String, company: String? = nil, groupVisitId: Int? = nil) {
        self.mobileNumber = mobileNumber
        self.notificationTriggers = notificationTriggers
        self.firstName = firstName
        self.emailTemplateId = emailTemplateId
        self.customFields = customFields
        self.hostIds = hostIds
        self.watchlistColour = watchlistColour
        self.title = title
        self.startDate = startDate
        self.lastName = lastName
        self.endDate = endDate
        self.email = email
        self.company = company
        self.groupVisitId = groupVisitId
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mobileNumber = "mobile_number"
        case notificationTriggers = "notification_triggers"
        case firstName = "first_name"
        case emailTemplateId = "email_template_id"
        case customFields = "custom_fields"
        case hostIds = "host_ids"
        case watchlistColour = "watchlist_colour"
        case title
        case startDate = "start_date"
        case lastName = "last_name"
        case endDate = "end_date"
        case email
        case company
        case groupVisitId = "group_visit_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mobileNumber, forKey: .mobileNumber)
        try container.encodeIfPresent(notificationTriggers, forKey: .notificationTriggers)
        try container.encode(firstName, forKey: .firstName)
        try container.encodeIfPresent(emailTemplateId, forKey: .emailTemplateId)
        try container.encodeIfPresent(customFields, forKey: .customFields)
        try container.encodeIfPresent(hostIds, forKey: .hostIds)
        try container.encodeIfPresent(watchlistColour, forKey: .watchlistColour)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(startDate, forKey: .startDate)
        try container.encode(lastName, forKey: .lastName)
        try container.encodeIfPresent(endDate, forKey: .endDate)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(company, forKey: .company)
        try container.encodeIfPresent(groupVisitId, forKey: .groupVisitId)
    }



}
