//
// PaginatedHostsList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PaginatedHostsList: Codable { 


    public var pagination: Pagination
    public var hosts: [Any]

    public init(pagination: Pagination, hosts: [Any]) {
        self.pagination = pagination
        self.hosts = hosts
    }

}
