//
// PaginatedPackagesList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PaginatedPackagesList: Codable { 


    public var packages: [Any]
    public var pagination: Any

    public init(packages: [Any], pagination: Any) {
        self.packages = packages
        self.pagination = pagination
    }

}
