//
// PaginatedInvitesList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PaginatedInvitesList: Codable { 


    public var invites: [Any]
    public var pagination: Any

    public init(invites: [Any], pagination: Any) {
        self.invites = invites
        self.pagination = pagination
    }

}
