//
// PaginatedAuditLogsList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/**  */
public struct PaginatedAuditLogsList: Codable, Hashable {

    public var pagination: Pagination
    public var auditLogs: [AuditLog]

    public init(pagination: Pagination, auditLogs: [AuditLog]) {
        self.pagination = pagination
        self.auditLogs = auditLogs
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pagination
        case auditLogs = "audit_logs"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pagination, forKey: .pagination)
        try container.encode(auditLogs, forKey: .auditLogs)
    }



}
