//
// PaginatedInvitesList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct PaginatedInvitesList: Codable, Hashable {

    public var invites: [Invite]
    public var pagination: Pagination

    public init(invites: [Invite], pagination: Pagination) {
        self.invites = invites
        self.pagination = pagination
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case invites
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(invites, forKey: .invites)
        try container.encode(pagination, forKey: .pagination)
    }



}
