//
// PaginatedEmailTemplatesList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PaginatedEmailTemplatesList: Codable { 


    public var pagination: Any
    public var emailTemplates: [Any]

    public init(pagination: Any, emailTemplates: [Any]) {
        self.pagination = pagination
        self.emailTemplates = emailTemplates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case pagination
        case emailTemplates = "email_templates"
    }

}
