//
// PaginatedAuditLogsList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PaginatedAuditLogsList: Codable { 


    public var pagination: Any
    public var auditLogs: [Any]

    public init(pagination: Any, auditLogs: [Any]) {
        self.pagination = pagination
        self.auditLogs = auditLogs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case pagination
        case auditLogs = "audit_logs"
    }

}
