//
// PaginatedPackagesList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct PaginatedPackagesList: Codable, Hashable {

    public var packages: [Package]
    public var pagination: Pagination

    public init(packages: [Package], pagination: Pagination) {
        self.packages = packages
        self.pagination = pagination
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case packages
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(packages, forKey: .packages)
        try container.encode(pagination, forKey: .pagination)
    }



}
