//
// PaginatedWatchlistList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PaginatedWatchlistList: Codable { 


    public var watchlists: [Any]
    public var pagination: Any

    public init(watchlists: [Any], pagination: Any) {
        self.watchlists = watchlists
        self.pagination = pagination
    }

}
