//
// PaginatedSigninsList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct PaginatedSigninsList: Codable, Hashable {

    public var pagination: Pagination
    public var signins: [Signin]

    public init(pagination: Pagination, signins: [Signin]) {
        self.pagination = pagination
        self.signins = signins
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pagination
        case signins
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pagination, forKey: .pagination)
        try container.encode(signins, forKey: .signins)
    }



}
