//
// PaginatedLocationsList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PaginatedLocationsList: Codable { 


    public var locations: [Any]
    public var pagination: Any

    public init(locations: [Any], pagination: Any) {
        self.locations = locations
        self.pagination = pagination
    }

}
