//
// PaginatedRegistrationsList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PaginatedRegistrationsList: Codable { 


    public var registrations: [Any]?
    public var pagination: Any?

    public init(registrations: [Any]?, pagination: Any?) {
        self.registrations = registrations
        self.pagination = pagination
    }

}
