//
// PaginatedLocationsList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct PaginatedLocationsList: Codable, Hashable {

    public var locations: [Location]
    public var pagination: Pagination

    public init(locations: [Location], pagination: Pagination) {
        self.locations = locations
        self.pagination = pagination
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case locations
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(locations, forKey: .locations)
        try container.encode(pagination, forKey: .pagination)
    }



}
