//
// PaginatedHostsList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct PaginatedHostsList: Codable, Hashable {

    public var pagination: Pagination
    public var hosts: [Host]

    public init(pagination: Pagination, hosts: [Host]) {
        self.pagination = pagination
        self.hosts = hosts
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pagination
        case hosts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pagination, forKey: .pagination)
        try container.encode(hosts, forKey: .hosts)
    }



}
