//
// PaginatedGroupVisitsList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  */
public struct PaginatedGroupVisitsList: Codable { 


    public var pagination: Pagination?
    public var groupVisits: [GroupVisit]?

    public init(pagination: Pagination?, groupVisits: [GroupVisit]?) {
        self.pagination = pagination
        self.groupVisits = groupVisits
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case pagination
        case groupVisits = "group_visits"
    }

}
