//
// PaginatedSigninsList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PaginatedSigninsList: Codable { 


    public var pagination: Any
    public var signins: [Any]

    public init(pagination: Any, signins: [Any]) {
        self.pagination = pagination
        self.signins = signins
    }

}
