//
// SigninDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** The root of the Signin type&#39;s schema. */
public struct SigninDetail: Codable, Hashable {

    public var id: Int
    public var documents: [SignableDocument]?
    public var signinWatchlist: SigninWatchlist?
    public var hosts: [Host]?
    public var signinData: [SigninData]?
    public var signinAcknowledgement: SigninAcknowledgement?
    public var note: String?
    /** A one-way method of Signing out a Signin */
    public var isSignedOut: Bool?
    public var signinTimestamp: Date?
    public var signinPhotoUrl: String?
    public var signedOutTimestamp: Date?
    public var mobileNumber: String?
    public var locationName: String?
    public var lastName: String?
    /** Whether this Signin has been acknowledged yet. Can also be used as a one-way method of setting the Signin as acknowledged. */
    public var isAcknowledged: Bool?
    public var isAccountedFor: Bool?
    public var firstName: String?
    public var email: String?
    public var company: String?
    public var registration: Registration?

    public init(id: Int, documents: [SignableDocument]? = nil, signinWatchlist: SigninWatchlist? = nil, hosts: [Host]? = nil, signinData: [SigninData]? = nil, signinAcknowledgement: SigninAcknowledgement? = nil, note: String? = nil, isSignedOut: Bool? = nil, signinTimestamp: Date? = nil, signinPhotoUrl: String? = nil, signedOutTimestamp: Date? = nil, mobileNumber: String? = nil, locationName: String? = nil, lastName: String? = nil, isAcknowledged: Bool? = nil, isAccountedFor: Bool? = nil, firstName: String? = nil, email: String? = nil, company: String? = nil, registration: Registration? = nil) {
        self.id = id
        self.documents = documents
        self.signinWatchlist = signinWatchlist
        self.hosts = hosts
        self.signinData = signinData
        self.signinAcknowledgement = signinAcknowledgement
        self.note = note
        self.isSignedOut = isSignedOut
        self.signinTimestamp = signinTimestamp
        self.signinPhotoUrl = signinPhotoUrl
        self.signedOutTimestamp = signedOutTimestamp
        self.mobileNumber = mobileNumber
        self.locationName = locationName
        self.lastName = lastName
        self.isAcknowledged = isAcknowledged
        self.isAccountedFor = isAccountedFor
        self.firstName = firstName
        self.email = email
        self.company = company
        self.registration = registration
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case documents
        case signinWatchlist = "signin_watchlist"
        case hosts
        case signinData = "signin_data"
        case signinAcknowledgement = "signin_acknowledgement"
        case note
        case isSignedOut = "is_signed_out"
        case signinTimestamp = "signin_timestamp"
        case signinPhotoUrl = "signin_photo_url"
        case signedOutTimestamp = "signed_out_timestamp"
        case mobileNumber = "mobile_number"
        case locationName = "location_name"
        case lastName = "last_name"
        case isAcknowledged = "is_acknowledged"
        case isAccountedFor = "is_accounted_for"
        case firstName = "first_name"
        case email
        case company
        case registration
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(documents, forKey: .documents)
        try container.encodeIfPresent(signinWatchlist, forKey: .signinWatchlist)
        try container.encodeIfPresent(hosts, forKey: .hosts)
        try container.encodeIfPresent(signinData, forKey: .signinData)
        try container.encodeIfPresent(signinAcknowledgement, forKey: .signinAcknowledgement)
        try container.encodeIfPresent(note, forKey: .note)
        try container.encodeIfPresent(isSignedOut, forKey: .isSignedOut)
        try container.encodeIfPresent(signinTimestamp, forKey: .signinTimestamp)
        try container.encodeIfPresent(signinPhotoUrl, forKey: .signinPhotoUrl)
        try container.encodeIfPresent(signedOutTimestamp, forKey: .signedOutTimestamp)
        try container.encodeIfPresent(mobileNumber, forKey: .mobileNumber)
        try container.encodeIfPresent(locationName, forKey: .locationName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(isAcknowledged, forKey: .isAcknowledged)
        try container.encodeIfPresent(isAccountedFor, forKey: .isAccountedFor)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(company, forKey: .company)
        try container.encodeIfPresent(registration, forKey: .registration)
    }



}
