//
// SigninData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SigninData: Codable { 


    public var customFields: [Any]?
    public var name: String?

    public init(customFields: [Any]?, name: String?) {
        self.customFields = customFields
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case customFields = "custom_fields"
        case name
    }

}
