//
// WatchlistCreateParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Parameters required for updating or creating watchlist records  */
public struct WatchlistCreateParams: Codable { 


    public enum Colour: String, Codable, CaseIterable {
        case red = "RED"
        case yellow = "YELLOW"
        case green = "GREEN"
        case orange = "ORANGE"
    }
    public var aliases: [String]?
    public var notes: String?
    public var lastName: String?
    public var firstName: String?
    public var email: String?
    public var colour: Colour?
    /** A base64 encoded image. base64_image should be strict encoded  */
    public var base64Image: Data?
    public var driverLicense: String?

    public init(aliases: [String]?, notes: String?, lastName: String?, firstName: String?, email: String?, colour: Colour?, base64Image: Data?, driverLicense: String?) {
        self.aliases = aliases
        self.notes = notes
        self.lastName = lastName
        self.firstName = firstName
        self.email = email
        self.colour = colour
        self.base64Image = base64Image
        self.driverLicense = driverLicense
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case aliases
        case notes
        case lastName = "last_name"
        case firstName = "first_name"
        case email
        case colour
        case base64Image = "base64_image"
        case driverLicense = "driver_license"
    }

}
