//
// Watchlist.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The root of the Watchlist type&#39;s schema. */
public struct Watchlist: Codable { 


    public enum Colour: String, Codable, CaseIterable {
        case red = "RED"
        case yellow = "YELLOW"
        case green = "GREEN"
        case orange = "ORANGE"
    }
    public var id: Int
    public var aliases: [String]?
    public var photo: String?
    public var notes: String?
    public var lastName: String?
    public var firstName: String?
    public var email: String?
    public var colour: Colour?
    public var driverLicense: String?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(id: Int, aliases: [String]?, photo: String?, notes: String?, lastName: String?, firstName: String?, email: String?, colour: Colour?, driverLicense: String?, createdAt: Date?, updatedAt: Date?) {
        self.id = id
        self.aliases = aliases
        self.photo = photo
        self.notes = notes
        self.lastName = lastName
        self.firstName = firstName
        self.email = email
        self.colour = colour
        self.driverLicense = driverLicense
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case aliases
        case photo
        case notes
        case lastName = "last_name"
        case firstName = "first_name"
        case email
        case colour
        case driverLicense = "driver_license"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

}
